# SPDX-License-Identifier: GPL-2.0-only
# Copyright (C) 2018-2020 Serenity. All rights reserved.

LINUXINCLUDE += -I$(srctree)/

obj-$(CONFIG_MAPPED_PROTECT) += serenity_bsp_mapped_protect.o

serenity_bsp_mapped_protect-y := mapped_protect.o
